# Generated bytecode contains expressions only; caches and closures are created
# in the live application environment when those expressions are evaluated.
.cgv_compiled_manifest_cache <- new.env(parent = emptyenv())

cgv_compiled_expressions <- function(file) {
    if (tolower(Sys.getenv('APP_COMPILED_RUNTIME', '1')) %in% c('0', 'false', 'off')) return(NULL)
    root <- Sys.getenv('CGV_COMPILED_RUNTIME_DIR', '.cgv-compiled')
    manifest_path <- file.path(root, 'manifest.rds')
    if (!file.exists(manifest_path)) return(NULL)
    cache_key <- normalizePath(manifest_path, mustWork = FALSE)
    if (!exists(cache_key, envir = .cgv_compiled_manifest_cache, inherits = FALSE)) {
        manifest <- tryCatch(readRDS(manifest_path), error = function(e) NULL)
        valid <- is.list(manifest) && identical(manifest$schema, 1L) &&
            identical(manifest$r_version, R.version.string) &&
            identical(manifest$platform, R.version$platform) &&
            is.character(manifest$sources) && length(manifest$sources) > 0L &&
            !is.null(names(manifest$sources)) && all(file.exists(names(manifest$sources))) &&
            is.list(manifest$packages) && is.list(manifest$files) &&
            identical(tools::md5sum(names(manifest$sources)), manifest$sources)
        if (valid) {
            valid <- all(vapply(names(manifest$packages), function(pkg) {
                tryCatch(identical(as.character(utils::packageVersion(pkg)), manifest$packages[[pkg]]),
                         error = function(e) FALSE)
            }, logical(1)))
        }
        assign(cache_key, if (valid) manifest else FALSE, envir = .cgv_compiled_manifest_cache)
    }
    manifest <- get(cache_key, envir = .cgv_compiled_manifest_cache, inherits = FALSE)
    if (!is.list(manifest)) return(NULL)
    entry <- manifest$files[[file]]
    if (!is.list(entry) || !is.character(entry$artifact) || length(entry$artifact) != 1L ||
        is.na(entry$artifact) || !is.numeric(entry$expressions) || length(entry$expressions) != 1L ||
        is.na(entry$expressions) || !file.exists(file) ||
        !identical(unname(tools::md5sum(file)), entry$source_md5)) return(NULL)
    artifact_path <- file.path(root, entry$artifact)
    if (!file.exists(artifact_path) || !identical(unname(tools::md5sum(artifact_path)), entry$artifact_md5)) return(NULL)
    codes <- tryCatch(readRDS(artifact_path), error = function(e) NULL)
    if (!is.list(codes) || length(codes) != entry$expressions || !all(vapply(codes, function(x) identical(typeof(x), 'bytecode'), logical(1)))) return(NULL)
    codes
}

cgv_source_runtime <- function(file, envir) {
    codes <- cgv_compiled_expressions(file)
    if (is.null(codes)) return(sys.source(file, envir = envir))
    # Never retry source evaluation after a runtime error: earlier expressions
    # may already have performed their normal initialization side effects.
    for (code in codes) eval(code, envir)
    invisible(NULL)
}

cgv_runtime_server <- function(definition) {
    codes <- cgv_compiled_expressions('server.R')
    if (is.null(codes) || length(codes) != 1L) return(definition)
    value <- eval(codes[[1L]], environment(definition))
    stopifnot(is.function(value))
    value
}
